# ELKO Living System auto setup configuration.
# To customize this, copy this file to the Home Assistant configuration
# folder and make your changes.

binary_sensor:
  # Smoke detector
  - xpath: './/product_dataline[@product_identifier="_0x210a"]'
    node: "dataline_input"
    type: "smoke"
    inverting: true
  # Gas detector NC
  - xpath: './/product_dataline[@product_identifier="_0x210b"]'
    node: "dataline_input[1]"
    type: "gas"
    inverting: true
  # Gas detector NO
  - xpath: './/product_dataline[@product_identifier="_0x210b"]'
    node: "dataline_input[2]"
    type: "gas"
    inverting: false
  # Leak detector
  - xpath: './/product_dataline[@product_identifier="_0x210c"]'
    node: "dataline_input"
    type: "moisture"
  # PIR med skumringsdetektor
  - xpath: './/product_dataline[@product_identifier="_0x210e"]'
    node: "dataline_input[1]"
    type: "motion"
    inverting: true
  # PIR med skumringsdetektor
  - xpath: './/product_dataline[@product_identifier="_0x210e"]'
    node: "dataline_input[2]"
    type: "light"
    inverting: false
  # PIR alarm
  - xpath: './/product_dataline[@product_identifier="_0x210f"]'
    node: "dataline_input"
    type: "motion"
    inverting: true
  # Magnet contact
  - xpath: './/product_dataline[@product_identifier="_0x2109"]'
    node: "dataline_input"
    type: "opening"
    inverting: true
  # Light detector
  - xpath: './/product_dataline[@product_identifier="_0x2110"]'
    node: "dataline_input"
    type: "light"
    inverting: true
  # Sabotasjoealarm (NC)
  - xpath: './/product_dataline[@product_identifier="_0x2112"]'
    node: "dataline_input"
    type: "problem"
    inverting: true
  # Skumringsdetektor med solsensor
  - xpath: './/product_dataline[@product_identifier="_0x2114"]'
    node: "dataline_input"
    type: "light"
    inverting: true
  # Bakcupmodule battery 12V and 24V
  - xpath: './/product_dataline[@product_identifier="_0x2115"]'
    node: "dataline_input"
    type: "battery"
    inverting: true
  # PIR
  - xpath: './/product_dataline[@product_identifier="_0x2120"]'
    node: "dataline_input"
    type: "motion"
    inverting: true
  # IR fjernkontroll 8
  - xpath: './/product_dataline[@product_identifier="_0x211f"]'
    node: "dataline_input"
  # IR fjernkontroll 8
  - xpath: './/product_dataline[@product_identifier="_0x211f"]'
    node: "dataline_input"
  # IR fjernkontroll 16
  - xpath: './/product_dataline[@product_identifier="_0x210d"]'
    node: "dataline_input"
  # Tastatur for adgangskontroll
  - xpath: './/product_dataline[@product_identifier="_0x2111"]'
    node: "dataline_input"
  # For the buttons you can either configure as binary sensors, switches or both.
  # Just move the text to the switch section to make it a switch.
  # Trykk 1 knapp
  - xpath: './/product_dataline[@product_identifier="_0x2119"]'
    node: "dataline_input"
  # Trykk 1 knapp 1 LED
  - xpath: './/product_dataline[@product_identifier="_0x211a"]'
    node: "dataline_input"
  # Trykk 2 knapp 2 LED
  - xpath: './/product_dataline[@product_identifier="_0x211b"]'
    node: "dataline_input"
  # Trykk 2 knapp
  - xpath: './/product_dataline[@product_identifier="_0x2101"]'
    node: "dataline_input"
  # Trykk 3 knapp
  - xpath: './/product_dataline[@product_identifier="_0x2125"]'
    node: "dataline_input"
  # Trykk 3 knapp 3 LED
  - xpath: './/product_dataline[@product_identifier="_0x2126"]'
    node: "dataline_input"
  # Trykk 4 knapp 4 LED
  - xpath: './/product_dataline[@product_identifier="_0x2106"]'
    node: "dataline_input"
  # Trykk 5 knapp
  - xpath: './/product_dataline[@product_identifier="_0x2127"]'
    node: "dataline_input"
  # Trykk 6 knapp
  - xpath: './/product_dataline[@product_identifier="_0x2103"]'
    node: "dataline_input"
  # WL Trykk 4 knapp
  - xpath: './/product_airlink[@product_identifier="_0x4102"]'
    node: "airlink_input"
  # WL Fjernkontroll
  - xpath: './/product_airlink[@product_identifier="_0x4104"]'
    node: "airlink_input"
  # WL Nøkkelring
  - xpath: './/product_airlink[@product_identifier="_0x4105"]'
    node: "airlink_input"
  # WL Puck input
  - xpath: './/product_airlink[@product_identifier="_0x4106"]'
    node: "airlink_input"
  # Generic input product
  - xpath: './/product_dataline[@product_identifier="_0x2701"]'
    node: "dataline_output"

light:
  # WL Mobil dimmer 1-knapp
  - xpath: './/product_airlink[@product_identifier="_0x4301"]'
    node: "airlink_dimming"
    dimmable: true
  # WL Lampedimmer 1-knapp
  - xpath: './/product_airlink[@product_identifier="_0x4302"]'
    node: "airlink_dimming"
    dimmable: true
  # WL Mobil dimmer 2-knapp
  - xpath: './/product_airlink[@product_identifier="_0x4303"]'
    node: "airlink_dimming"
    dimmable: true
  # WL Lampedimmer 2-knapp
  - xpath: './/product_airlink[@product_identifier="_0x4304"]'
    node: "airlink_dimming"
    dimmable: true
  # WL Universel dimmer 1-knapp
  - xpath: './/product_airlink[@product_identifier="_0x4305"]'
    node: "airlink_dimming"
    dimmable: true
  # WL Universel dimmer 2-knapp
  - xpath: './/product_airlink[@product_identifier="_0x4306"]'
    node: "airlink_dimming"
    dimmable: true
  # WL 3-tråds Dimmer Puck 1-Knapp
  - xpath: './/product_airlink[@product_identifier="_0x4307"]'
    node: "airlink_dimming"
    dimmable: true
  # WL 3-tråds Dimmer Puck 2-Knapp
  - xpath: './/product_airlink[@product_identifier="_0x4308"]'
    node: "airlink_dimming"
    dimmable: true
  # Unidimmer 1-knapp
  - xpath: './/product_dataline[@product_identifier="_0x2301"]'
    node: "dataline_output"
    dimmable: true
  # Unidimmer 2-knapp
  - xpath: './/product_dataline[@product_identifier="_0x2302"]'
    node: "dataline_output"
    dimmable: true
  # Dimmer 1-knapp
  - xpath: './/product_dataline[@product_identifier="_0x2303"]'
    node: "dataline_output"
    dimmable: true
  # Dimmer 2-knapp
  - xpath: './/product_dataline[@product_identifier="_0x2304"]'
    node: "dataline_output"
    dimmable: true
  # Lampeuttak
  - xpath: './/product_dataline[@product_identifier="_0x2202"]'
    node: "dataline_output"
    dimmable: false
  # WL Lampeuttak
  - xpath: './/product_airlink[@product_identifier="_0x2202"]'
    node: "dataline_output"
    dimmable: false

sensor:
  # Temperature sensor
  - xpath: './/product_dataline[@product_identifier="_0x2124"]'
    node: "resource_temperature"
    unit_of_measurement: "°C"
  # Humidity/temperature
  - xpath: './/product_dataline[@product_identifier="_0x2135"]'
    node: "resource_humidity_level"
    unit_of_measurement: "%"
  # Lux/temperature
  - xpath: './/product_dataline[@product_identifier="_0x2136"]'
    node: "resource_light"
    unit_of_measurement: "Lux"
  # Temperature sensor ELKO
  - xpath: './/product_dataline[@product_identifier="_0x2122"]'
    node: "resource_temperature"
    unit_of_measurement: "°C"

switch:
  # Kontaktrelé
  - xpath: './/product_dataline[@product_identifier="_0x2201"]'
    node: "dataline_output"
  # Intern sirene 80dB og 102 dB
  - xpath: './/product_dataline[@product_identifier="_0x2203"]'
    node: "dataline_output"
  # Ekstern sirene
  - xpath: './/product_dataline[@product_identifier="_0x2204"]'
    node: "dataline_output"
  # Solenoidventil NC. Ventilen er lukket så lenge 230V blir tilført.
  - xpath: './/product_dataline[@product_identifier="_0x2205"]'
    node: "dataline_output"
  # Solenoidventil NO. Ventilen er åpen så lenge 230V blir tilført.
  - xpath: './/product_dataline[@product_identifier="_0x2206"]'
    node: "dataline_output"
  # Outputmodul 1-10V
  - xpath: './/product_dataline[@product_identifier="_0x2207"]'
    node: "dataline_output"
  # Doorlock
  - xpath: './/product_dataline[@product_identifier="_0x2208"]'
    node: "dataline_output"
  # Doorbell
  - xpath: './/product_dataline[@product_identifier="_0x2209"]'
    node: "dataline_output"
  # Varmeanlegg gulvvarme
  - xpath: './/product_dataline[@product_identifier="_0x2210"]'
    node: "dataline_output"
  # Generic output product
  - xpath: './/product_dataline[@product_identifier="_0x2702"]'
    node: "dataline_output"
  # Wireless Plug outlet
  - xpath: './/product_airlink[@product_identifier="_0x4201"]'
    node: "airlink_relay"
  # WL Universelt relé
  - xpath: './/product_airlink[@product_identifier="_0x4203"]'
    node: "airlink_relay"
  # WL Mobil relé
  - xpath: './/product_airlink[@product_identifier="_0x4204"]'
    node: "airlink_relay"
  # WL Puck relé
  - xpath: './/product_airlink[@product_identifier="_0x4205"]'
    node: "airlink_relay"
  # WL Persienne/shutter (2 knapp, lokal lås)
  - xpath: './/product_airlink[@product_identifier="_0x45015"]'
    node: "airlink_shutter"
